In [1]:
import pandas as pd
df = pd.read_excel(r"D:\ML\DATA_SCIENCE\Task 5 Equality Table.xlsx")

In [2]:
df.head()

,Factory,Job Role,Equality Score,Equality class,Equality Class
0,Daikibo Factory Meiyo,C-Level,-25,NaN,Highly Discriminative
1,Daikibo Factory Meiyo,VP,-26,NaN,Highly Discriminative
2,Daikibo Factory Meiyo,Director,-19,NaN,Unfair
3,Daikibo Factory Meiyo,Sr. Manager,-15,NaN,Unfair
4,Daikibo Factory Meiyo,Manager,-14,NaN,Unfair

In [3]:
def classify_equality(num):
  abs_number = abs(num)
  if abs_number <= 10:
    return 'Fair'
  elif abs_number <= 20:
    return 'Unfair'
  else:
    return 'Highly Discriminative'

df['Equality Class'] = df['Equality Score'].apply(classify_equality)

df[['Equality Score' , 'Equality Class']].head(10)

   Equality Score         Equality Class
0             -25  Highly Discriminative
1             -26  Highly Discriminative
2             -19                 Unfair
3             -15                 Unfair
4             -14                 Unfair
5             -20                 Unfair
6              -5                   Fair
7              -8                   Fair
8               3                   Fair
9             -22  Highly Discriminative

In [ ]:
def login(username,password:list[int])->str :

  return f'{username} his pasword {password}'


login('john',[12,3,23])

'john his pasword [12, 3, 23]'